[tool.poetry]
name = "四分木"
version = "0.1.0"
description = ""
authors = ["dsjt"]

[tool.poetry.dependencies]
python = "^3.9"
matplotlib = "^3.4.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
